# Read config dir of python
# The following task can only be performaned after the requirements
# are installed
- name: Store configdir of Python
  shell: python3-config --configdir
  register: vim_python3

- set_fact:
    vim_python3_lib: "{{ vim_python3.stdout }}"

- name: Cloning VIM repository
  git:
    repo: '{{ vim_remote_git_repo }}'
    dest: '{{ vim_repo_path }}'

- name: Check whether VIM was already build
  stat:
    path: '{{ vim_repo_path}}/src/vim'
  register: vim_is_build

- debug: msg="VIM is build already"
  when: vim_is_build.stat.exists == True 

- name: Cleanup source directory
  make:
    target: distclean
    chdir: '{{ vim_repo_path }}' 

- name: Run Configure
  shell: "{{ vim_configure}}"
  args:
    chdir: '{{ vim_repo_path }}' 
  when: vim_is_build.stat.exists == False

- name: Make VIM
  make:
    chdir: '{{ vim_repo_path }}' 
  when: vim_is_build.stat.exists == False

- name: Install VIM
  make:
    target: install
    chdir: '{{ vim_repo_path }}' 
  become: yes

- name: Remove configure log
  file:
    path: "{{ vim_configure_log }}"
    state: absent

- name: Set alias for build vim
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias vim='{{ vim_install_dir }}/bin/vim'"
    create: yes
  when: vim_set_alias == True

- name: Set alias for build vimdiff
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias vimdiff='{{ vim_install_dir }}/bin/vimdiff'"
    create: yes
  when: vim_set_alias == True
