- name: Cloning VIM repository
  git:
    repo: '{{ vim_remote_git_repo }}'
    dest: '{{ vim_repo_path }}'

- name: Check whether VIM was already build
  stat:
    path: '{{ vim_repo_path}}/src/vim'
  register: vim_is_build

- debug: msg="VIM is build already"
  when: vim_is_build.stat.exists == True 

- name: Run Configure
  shell: "{{ vim_configure}}"
  args:
    chdir: '{{ vim_repo_path }}' 
  when: vim_is_build.stat.exists == False

- name: Make VIM
  make:
    chdir: '{{ vim_repo_path }}' 
  when: vim_is_build.stat.exists == False

- name: Install VIM
  make:
    target: install
    chdir: '{{ vim_repo_path }}' 
  become: yes

- name: Remove configure log
  file:
    path: "{{ vim_configure_log }}"
    state: absent

- name: Set alias for build vim
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "alias wim='{{ vim_install_dir }}/bin/vim'"
    create: yes
