- name: Check wheter GIT is available
  stat: 
    path: "{{vim_git_executable}}"
  register: vim_has_git

- fail: 
    msg: "No GIT available"
  when: vim_has_git.stat.exists == False

- include_tasks: setup-ubuntu.yml
  when: ansible_os_family == "Ubuntu"

- include_tasks: setup-suse.yml
  when: ansible_os_family == "Suse"

- include_tasks: setup-macos.yml
  when: ansible_os_family == "Darwin"

- name: Check whether VIM was already build
  stat:
    path: '{{ vim_repo_path}}/src/vim'
  register: vim_is_build

- debug: msg="VIM is build already"
  when: vim_is_build.stat.exists == True 

# Build VIM is not already build
- include_tasks: build-vim.yml
  when: vim_is_build.stat.exists == False

# Configure VIM 
- include_tasks: configure-vim.yml
