- name: Check wheter GIT is available
  stat: 
    path: "{{vim_git_executable}}"
  register: vim_has_git

- fail: 
    msg: "No GIT available"
  when: vim_has_git.stat.exists == False


- name: Install dependencies
  apt: name={{item}} state=installed
  with_items:
    - libncurses-dev
    - liblua5.1-dev 
    - luajit
    - libluajit-5.1-dev
    - libperl-dev
    - python-dev
    - python3-dev
    - ruby-dev
    - libatk1.0-dev 
    - libx11-dev 
    - libxpm-dev 
    - libxt-dev
 
- name: Cloning VIM repository
  git:
    repo: 'https://github.com/vim/vim'
    dest: '{{ vim_repo_path }}'

- name: Check whether VIM was already build
  stat:
    path: '{{ vim_repo_path}}/src/vim'
  register: vim_is_build

- debug: msg="VIM is build already"
  when: vim_is_build.stat.exists == True 

- name: Run Configure
  shell: "{{ vim_configure}}"
  args:
    chdir: '{{ vim_repo_path }}' 
  when: vim_is_build.stat.exists == False

- name: Make VIM
  make:
    chdir: '{{ vim_repo_path }}' 
  when: vim_is_build.stat.exists == False

- name: Install VIM
  make:
    target: install
    chdir: '{{ vim_repo_path }}' 
  become: yes
