# Check if GIT is available
- name: Check wheter GIT is available
  stat: 
    path: "{{vim_git_executable}}"
  register: vim_has_git

- fail: 
    msg: "No GIT available"
  when: vim_has_git.stat.exists == False

# Install requirements based on OS family
- name: Install requirements for Ubuntu/Debian
  include_tasks: setup-ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Install requirements for Suse
  include_tasks: setup-suse.yml
  when: ansible_os_family == "Suse"

- name: Install requirements for MacOS
  include_tasks: setup-macos.yml
  when: ansible_os_family == "Darwin"

# Build VIM is not already build
- include_tasks: build-vim.yml
  when: vim_build_from_source == True

# Configure VIM 
- include_tasks: configure-vim.yml
